server:
  port: 9909
logging:
  level:
    org.springframework.web: INFO
    com.github.binarywang.demo.wx.mp: DEBUG
    me.chanjar.weixin: DEBUG
api:
  chatgpt:
    url: xxxx
wx:
  mp:
    useRedis: false
    redisConfig:
      host: 127.0.0.1
      port: 6379
      password:
    configs:
      - appId: xxx # 第一个公众号的appid
        secret: xxx # 公众号的appsecret
        token: xxx # 接口配置里的Token值
        aesKey: xxx # 接口配置里的EncodingAESKey值
